name: Kodi Addon-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: kodi addon check
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: validate addon for leia
        uses: xbmc/action-kodi-addon-checker@v1.2
        with:
          kodi-version: leia
          addon-id: ${{ github.event.repository.name }}
      - name: validate addon for matrix
        uses: xbmc/action-kodi-addon-checker@v1.2
        with:
          kodi-version: matrix
          rewrite-for-matrix: true
          addon-id: ${{ github.event.repository.name }}
