
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - uses: dschep/install-pipenv-action@v1
    - name: install dependencies
      run: pipenv install -d
    - name: run python3 lint
      run: pipenv run lint
    - name: run tests
      run: pipenv run test
